-- Databricks notebook source
-- DBTITLE 1,1. Creación de tabla "Tablon" en la capa Gold - DELTA
DROP DATABASE IF EXISTS GOLD_RETAIL CASCADE;

CREATE SCHEMA IF NOT EXISTS GOLD_RETAIL;

DROP TABLE IF EXISTS GOLD_RETAIL.TABLON;

CREATE TABLE GOLD_RETAIL.TABLON(
ID_PERSONA STRING,
NOMBRE_PERSONA STRING,
EDAD_PERSONA INT,
SALARIO_PERSONA DOUBLE,
ID_EMPRESA STRING,
NOMBRE_EMPRESA STRING,
MONTO_TRANSACCION DOUBLE,
FECHA STRING
)
USING DELTA
LOCATION 'dbfs:/mnt/lakehousedata/gold/tablon/'
PARTITIONED BY (FECHA);

-- COMMAND ----------

-- MAGIC %py
-- MAGIC spark.sql(""" SET hive.exec.dynamic.partition.mode=nonstrict """)

-- COMMAND ----------

-- DBTITLE 1,2. Carga curada a la tabla "Tablon" en la capa Gold
INSERT OVERWRITE TABLE GOLD_RETAIL.TABLON
SELECT LS_PER.ID,LS_PER.NOMBRE,LS_PER.EDAD,LS_PER.SALARIO,LS_EMP.ID, LS_EMP.NOMBRE, LS_TRX.MONTO, LS_TRX.FECHA
FROM SILVER_RETAIL.CLIENTE LS_PER
JOIN SILVER_RETAIL.EMPRESA LS_EMP ON (LS_PER.ID_EMPRESA = LS_EMP.ID) 
JOIN SILVER_RETAIL.VENTA LS_TRX ON (LS_TRX.ID_PERSONA = LS_TRX.ID_PERSONA) 
;

-- COMMAND ----------

-- DBTITLE 1,3. Validación de datos cargados a la tabla "Tablon" en la capa Gold
--REFRESH TABLE GOLD_RETAIL.TABLON;

SELECT * FROM GOLD_RETAIL.TABLON;

-- COMMAND ----------

SELECT * FROM SILVER_RETAIL.EMPRESA
